import math

###========================###
###		OPTIONS INPUT 	   ###
###========================###
includeMT = True 			# If true, MT are included
includeAc = True 			# If true, Actin is included
includeAcMT = True 			# If true, crosslinks between MT and actin are included
stabDistalMT = True			# If true, distal set of MT do not (de)polymerize
plotOutput = True			# If true, paraview output is plotted

optionYZ = 0				# If 0, all yz coordinates fixed, else yz disp is constant in each MT
optionBC = 0				# If 0, load control, else disp control

###========================###
###		GEOMETRY INPUT 	   ###
###========================###

nc     = 2					# [-] 1 or 2, indicates how many circumferencetial layers we have.
rInner = 90;				# [nm]
rAxon  = 3*rInner			# [nm]
rConn  = rInner*1.8;		# [nm] Maximum distance within cross-section where cross-link is made
nMT = 7 if nc == 1 else 19  # [-] Number of MT in one cross section

lMT0    = 2500.				# [nm] Initial Length of a single MT
lMTMax  = 2.0*lMT0 			# [nm] Length of MT that can be added by polymerization (determines how many storage elements we need)
lAxon  = 1.0*lMTMax			# [nm] Length of the modeled axon
lGap   = 0.01*lMTMax		# [nm] Length of gap in between two successive mt
dlGC   = .5*lMT0			# [nm] Distance between end of axon and the growth cone node

nAcCirc = 12;				# [-] number of actin cells in circumferential direction
dlActinRing = 500.; 			# [nm] Distance between neigboring actin rings
lActin = dlActinRing*1.5	# [nm] Length of one actin filament in longitudinal direction
rFracActin = 1.1			# [-] fraction of radius outer actin ring layer w.r.t axon radius


dlLink_MT_MT = 1.		# [nm] Gap in between two crosslinks between two MT's
thLink_MT_MT = 30.*math.pi/180.		# [rad] Angle of crosslinks wrt to orthogonal

dlLink_MT_Ac = 1.			 		# [nm] Gap in between two crosslinks between MT and actin
thLink_MT_Ac = 30.*math.pi/180.		# [rad] Angle of crosslinks wrt to orthogonal

dlLink_Ac_Ac = 1.5			 		# [nm] Gap in between two crosslinks between actin
thLink_Ac_Ac = 75.*math.pi/180.		# [rad] Angle of crosslinks wrt to orthogonal

lCL_Ac_Ac = 1.;						# [nm] Typical length of a crosslink between actin and actin
fCl_Ac_Ac = 1.      				# [-] Fraction of potential crosslinks that are actually attached

###========================###
###		 MATERIAL INPUT    ###
###========================###
E_MT   	= 1200.0			# [MPa] Microtubule stiffness
E_Ac = 1200.0 				# [MPa] Actin stiffness
E_Dyn   = 70.				# [MPa] Dynein stiffness
E_Myo   = 40.				# [MPa] Myosin stiffness
E_MT_Ac = 40.				# [MPa] MT Ac crosslink stiffness
E_GC   = 1200.;				# [MPa] Growth cone connection stiffness
E_Med   = 0.e-1;			# [MPa] Medium stiffness
eta_Ac=  200.				# [MPa*s] Viscosity of actin
eta_Med = 1.e-8				# [MPa*s] Viscosity of surrounding medium (water)

area_MT  = 400.0			# [nm2] Initial corss-sectional area of MT
area_Ac = 1000. 				# [nm2] Initial corss-sectional area of actin
area_Dyn   = 1.0				# [nm2] Initial cross-sectional area of dynein
area_Myo   = 1.0				# [nm2] Initial cross-sectional area of myosin
area_MT_Ac = 1.0				# [nm2] Initial cross-sectional area of MT Ac crosslinks
area_GC   = 1000.;				# [nm2] Initial cross-sectional area of GC connections

force_Dyn = 0.0				# [pN] Force generated by dynein
force_Ac = 0.0				# [pN] Force generated by actin
force_Myo = 0.0/3.			# [pN] Force generated by myosin

# Dynein
minInitStretch_Dyn = 0.09	# [-] Minimum initial stretch of dynein
minStretch_Dyn = 0.09		# [-] Minimum stretch of dynein

maxInitStretch_Dyn = 1.02	# [-] Maximum initial stretch of dynein
maxStretch_Dyn = 1.5		# [-] Maximum stretch of dynein

activeStretch_Dyn = 0.95	# [-] Active (contraction) stretch of dynein

optionDynein = 0			# [-] 0 - cross links ordered to yield extension
							#     1 - cross links not ordered (to yield neither extension or contraction)
							# 	  2 - cross links ordered to yield contraction

# Myosin
minInitStretch_Myo = 0.95	# [-] Minimum initial stretch of myosin
minStretch_Myo = 0.8		# [-] Minimum stretch of myosin

maxInitStretch_Myo = 1.02	# [-] Maximum initial stretch of myosin
maxStretch_Myo = 1.5		# [-] Maximum stretch of myosin

activeStretch_Myo = 0.9		# [-] Active (contraction) stretch of myosin

###========================###
###		 MESH/BC INPUT 	   ###
###========================###
dl_MT  = 3. 				# [nm] element length of MT
dl_Ac  = 2.#*lAxon 			# [nm] element length of Actin

# Load
loadExt = 250.				# [pN] Force applied at right side
dispExt = 0.				# [nm] Displ applied at right side

###========================###
###		 SOLVER INPUT 	   ###
###========================###

maxIter = 10;				# [-] Maximum number of iterations per step (if exceeded, dt decreases)
maxIterInc = 6;				# [-] Maximum number of iterations per step to allow increase in dt
maxStep = 1000;				# [-] Maximum number of steps (if exceeded, simulations stops)
tLoad = 0.1;				# [s] Time in which load is applied
tHold = 2.-tLoad			# [s] Hold time at beginning of simulation
tFinalLoad = 0.				# [s] Time in which final load after holding is applied
tEnd = tHold+tLoad+tFinalLoad 		# [s] End time of simulation
dt0  = 0.025;				# [s] Initial time step
dtMin = dt0/100.;			# [s] Minimum time step
dtMax = dt0;				# [s] Maximum time step
tolerance = 1.e-6;			# [-] Tolerance for convergence

###========================###
###		  TIME INPUT 	   ###
###========================###

# Dynein
#tDest = 180.				# [s] Crosslink destruction time random between 0-tDest 
#tCrea = 1.*tDest 			# [s] Crosslink creation time random between 0-tCrea 
tCont_Dyn = 0.15				# [s] Time between attachment and contraction random between 0-tCont 
tDest_Dyn = 0.1			# [s] Time between contraction and detachment random between 0-tDest 
tCrea_Dyn = tDest_Dyn+tCont_Dyn # [s] Time between detachment and attachment random between 0-tCrea 
fracForce_Dyn = 1.;			# [-] Fraction of Dynein crosslinks that are force generating. Others aren't

# Tau (alternative for dynein)
tDest_Tau = 200.			# [s] Time between contraction and detachment random between 0-tDest 
tCrea_Tau = tDest_Tau  		# [s] Time between detachment and attachment random between 0-tCrea 

# Microtubules
tMTpoly = 15.				# [s] Polymerization time random between 0-tMTpoly 
tMTstat = 0.001 		    # [s] Stationary time random between 0-tMTstat
tMTdepoly = 15. 			# [s] Depolymerization time random between 0-tMTdepoly
fracLMT   = 1.				# [-] Fraction that determines how much MT dynamics is controlled by target mt-length
					# 0 - no control; 1 - purely controlled by target
MTpolyRate = 2*5000.e-2			# [nm/s] Rate of polymerization MT (length/time)
MTdepolyRate = 2*5000.e-2	 		# [nm/s] Rate of depolymerization MT (length/time)

# Myosin
tCont_Myo = .6				# [s] Time between attachment and contraction random between 0-tCont 
tDest_Myo = .4			# [s] Time between contraction and detachment random between 0-tDest 
tCrea_Myo = tDest_Myo+tCont_Myo # [s] Time between detachment and attachment random between 0-tCrea 
fracForce_Myo = 1.;			# [-] Fraction of Myosin crosslinks that are force generating. Others aren't


# MT Ac crosslinks input
tDest_MT_Ac = 2.				# [s] Crosslink destruction time random between 0-tDest 
tCrea_MT_Ac = 1.*tDest_MT_Ac 	# [s] Crosslink creation time random between 0-tCrea 

